repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280  # ここに特定のバージョンを指定
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--strict"]
  - repo: local
    hooks:
      - id: check-licenses
        name: Check licenses
        entry: bash -c "pip-licenses --from=mixed --format=json | jq '.[] | select(.License == \"GPL\")' && exit 1 || exit 0"
        language: system
        types: [python]
