version: '3.8'  # 必要に応じてバージョンを指定
services:
  db:
    image: postgres:17.2
    container_name: postgres_container_0207
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_0207:/var/lib/postgresql/data
volumes:
  postgres_0207:
