version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # OpenTelemetry の HTTP トレース受信
      - "14250:14250"   # OpenTelemetry の gRPC トレース受信
      - "6831:6831/udp" # Jaeger エージェント（UDP）
      - "4317:4317"     # OpenTelemetry Protocol (OTLP)
